apps/blog/urls.py
from django.urls import path
from apps.blog.views import blog, blog_detail


urlpatterns = [
    path('blog/', blog, name='blog'),
    path('blog-detail/<slug:slug>/', blog_detail, name='blog-detail'),
]

apps/contact/urls.py
from django.urls import path
from apps.contact.views import contact


urlpatterns = [
    path('contact/', contact, name='contact')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', include('apps.product.urls')),
    path('', include('apps.contact.urls')),
    path('', include('apps.blog.urls')),
    path('', include('apps.order.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

handler404 = "config.errors.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from apps.common.models import BaseModel
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify
from django.urls import reverse


class Category(BaseModel):
    name = models.CharField(max_length=225)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=225)

    def save(self, *args, **kwargs):  
        if not self.slug:
            self.slug = slugify(self.name)

        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    

class Tag(BaseModel):
    name = models.CharField(max_length=225)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=225)

    def save(self, *args, **kwargs):  
        if not self.slug:
            self.slug = slugify(self.name)

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Blog(BaseModel):
    name = models.CharField(max_length=225)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=225)
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='blogs/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    avtor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    
    def save(self, *args, **kwargs):  
        if not self.slug:
            self.slug = slugify(self.name)

        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("blog-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name
    

apps/contact/models.py
from django.db import models
from apps.common.models import BaseModel


class Contact(BaseModel):
    name = models.CharField(max_length=225, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)   
    message = models.TextField(null=True, blank=True) 

    def __str__(self):
        return self.name
    

apps/blog/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from apps.blog.models import Blog


class BlogAdminForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Blog
        fields = '__all__'
        

apps/blog/views.py
from django.shortcuts import render, redirect
from apps.blog.models import Category, Tag, Blog
from django.core.paginator import Paginator
from apps.common.models import SubEmail


def blog(request):
    page = request.GET.get('page')
    tag = request.GET.get('tag')
    cat = request.GET.get('cat')
    search = request.GET.get('query')

    blogs = Blog.objects.all()

    if request.method == "POST":
        email = request.POST.get("subemail")
        SubEmail.objects.create(
            email=email,
        )

        return redirect ('blog')

    if tag:
        blogs = blogs.filter(tags__slug__exact=tag)

    if cat:
        blogs = blogs.filter(category__slug__exact=cat)

    paginator = Paginator(blogs, 3)
    selected_page = paginator.get_page(page)

    context = {
        'blogs': selected_page,
    }

    return render(request, 'blog.html', context)

def blog_detail(request, slug):
    tag = request.GET.get('tag')
    cat = request.GET.get('cat')
    search = request.GET.get('query')

    blog = Blog.objects.get(slug__exact=slug)

    blogs = Blog.objects.all().order_by('-id')[:3]

    if request.method == "POST":
        email = request.POST.get("subemail")
        SubEmail.objects.create(
            email=email,
        )

        return redirect ('blog', blog.slug)

    if tag:
        blogs = blogs.filter(tags__slug__exact=tag)

    if cat:
        blogs = blogs.filter(category__slug__exact=cat)

    context = { 
        'blog': blog,
        'blogs': blogs,
    }

    return render(request, 'blog-detail.html', context)

apps/contact/views.py
from django.shortcuts import render, redirect
from apps.contact.models import Contact
from apps.common.models import SubEmail


def contact(request):
    cat = request.GET.get('cat')
    search = request.GET.get('query')

    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        Contact.objects.create(
            name=name,
            email=email,
            message=message,
        )

        return redirect('contact')
    
    if request.method == "POST":
        email = request.POST.get("subemail")
        SubEmail.objects.create(
            email=email,
        )

        return redirect ('contact')
    
    return render(request, 'contact.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Ogani by EduVector! </title>

    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&amp;display=swap"
        rel="stylesheet">

    <link rel="stylesheet" href="{% static '' %}css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="{% static '' %}css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="{% static '' %}css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="{% static '' %}css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="{% static '' %}css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="{% static '' %}css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="{% static '' %}css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="{% static '' %}css/style.css" type="text/css">
</head>

<body>

    <div id="preloder">
        <div class="loader"></div>
    </div>

    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="{% url 'index' %}"><img src="{% static '' %}img/logo.png" alt></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="{% url 'wishlist' %}"><i class="fa fa-heart"></i> <span>{{ wishlist_count }}</span></a></li>
                <li><a href="{% url 'cart' %}"><i class="fa fa-shopping-bag"></i> <span>{{ cart_items_count }}</span></a></li>
            </ul>
            <div class="header__cart__price">Item: <span>${{ cart_total }}</span></div>
        </div>
        <div class="humberger__menu__widget">
            <div class="header__top__right__language">
                <img src="{% static '' %}img/language.png" alt>
                <div>English</div>
                <span class="arrow_carrot-down"></span>
                <ul>
                    <li><a href="#">Spanis</a></li>
                    <li><a href="#">English</a></li>
                </ul>
            </div>
            <div class="header__top__right__auth">
                <a href="#"><i class="fa fa-user"></i>Login</a>
            </div>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li class="active"><a href="{% url 'index' %}">Home</a></li>
                <li class="active"><a href="{% url 'shop' %}">Shop</a></li>
                <li class="active"><a href="{% url 'blog' %}">Blog</a></li>
                <li class="active"><a href="{% url 'contact' %}">Contact</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
            <a href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a>
            <a href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a>
            <a href="https://www.pinterest.com/"><i class="fa fa-pinterest-p"></i></a>
        </div>
        <div class="humberger__menu__contact">
            <ul>
                <li><i class="fa fa-envelope"></i> <a href="https://preview.colorlib.com/cdn-cgi/l/email-protection"
                        class="__cf_email__"
                        data-cfemail="9af2fff6f6f5daf9f5f6f5e8f6f3f8b4f9f5f7">[email&#160;protected]</a></li>
                <li>Free Shipping for all Order of $99</li>
            </ul>
        </div>
    </div>


    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                                <li><i class="fa fa-envelope"></i> <a
                                        href="https://preview.colorlib.com/cdn-cgi/l/email-protection"
                                        class="__cf_email__"
                                        data-cfemail="543c3138383b14373b383b26383d367a373b39">[email&#160;protected]</a>
                                </li>
                                <li>Free Shipping for all Order of $99</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                                <a href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a>
                                <a href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a>
                                <a href="https://www.pinterest.com/"><i class="fa fa-pinterest-p"></i></a>
                            </div>
                            <div class="header__top__right__language">
                                <img src="{% static '' %}img/language.png" alt>
                                <div>English</div>
                                <span class="arrow_carrot-down"></span>
                                <ul>
                                    <li><a href="#">Spanis</a></li>
                                    <li><a href="#">English</a></li>
                                </ul>
                            </div>
                            <div class="header__top__right__auth">
                                <a href="#"><i class="fa fa-user"></i> Login</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="{% url 'index' %}"><img src="{% static '' %}img/logo.png" alt></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="{% url 'index' %}">Home</a></li>
                            <li class="active"><a href="{% url 'shop' %}">Shop</a></li>
                            <li class="active"><a href="{% url 'blog' %}">Blog</a></li>
                            <li class="active"><a href="{% url 'contact' %}">Contact</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        <ul>
                          <li><a href="{% url 'wishlist' %}"><i class="fa fa-heart"></i> <span>{{ wishlist_count }}</span></a></li>
                          <li><a href="{% url 'cart' %}"><i class="fa fa-shopping-bag"></i> <span>{{ cart_items_count }}</span></a></li>
                        </ul>
                        <div class="header__cart__price">Item: <span>$ {{ cart_total }} </span></div>
                      </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>

    {% block content %}

    {% endblock %}

    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="{% url 'index' %}"><img src="{% static '' %}img/logo.png" alt></a>
                        </div>
                        <ul>
                            <li>Address: 60-49 Road 11378 New York</li>
                            <li>Phone: +65 11.188.888</li>
                            <li>Email: <a href="https://preview.colorlib.com/cdn-cgi/l/email-protection"
                                    class="__cf_email__"
                                    data-cfemail="acc4c9c0c0c3eccfc3c0c3dec0c5ce82cfc3c1">[email&#160;protected]</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Useful Links</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">About Our Shop</a></li>
                            <li><a href="#">Secure Shopping</a></li>
                            <li><a href="#">Delivery infomation</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Our Sitemap</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Who We Are</a></li>
                            <li><a href="#">Our Services</a></li>
                            <li><a href="#">Projects</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Innovation</a></li>
                            <li><a href="#">Testimonials</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Join Our Newsletter Now</h6>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#" method="post">

                            {% csrf_token %}

                            <input type="text" name="subemail" placeholder="Enter your mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                            <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
                            <a href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a>
                            <a href="https://www.pinterest.com/"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__copyright">
                        <div class="footer__copyright__text">
                            <p>
                                Copyright &copy;
                                <script data-cfasync="false"
                                    src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                                template is made
                                with <i class="fa fa-heart" aria-hidden="true"></i> by <a
                                    href="https://t.me/vectorzafar/" target="_blank">EduVector</a>
                            </p>
                        </div>
                        <div class="footer__copyright__payment"><img src="{% static '' %}img/payment-item.png" alt>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    {% block js %}

    {% endblock %}

    <script src="{% static '' %}js/jquery-3.3.1.min.js"></script>
    <script src="{% static '' %}js/bootstrap.min.js"></script>
    <script src="{% static '' %}js/jquery.nice-select.min.js"></script>
    <script src="{% static '' %}js/jquery-ui.min.js"></script>
    <script src="{% static '' %}js/jquery.slicknav.js"></script>
    <script src="{% static '' %}js/mixitup.min.js"></script>
    <script src="{% static '' %}js/owl.carousel.min.js"></script>
    <script src="{% static '' %}js/main.js"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
    <script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015"
        integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ=="
        data-cf-beacon='{"rayId":"897cde453a4b2d77","b":1,"version":"2024.4.1","token":"cd0b4b3a733644fc843ef0b185f98241"}'
        crossorigin="anonymous"></script>
</body>

</html>
 

templates/blog-detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="hero hero-normal">
  <div class="container">
    <div class="row">
      
      {% include 'categories.html' %}
      
      <div class="col-lg-9">
        <div class="hero__search">
          <div class="hero__search__form">
            <form action="#">
              <div class="hero__search__categories">
                All Categories
                <span class="arrow_carrot-down"></span>
              </div>
              <input type="text" name="query" placeholder="What do yo u need?">
              <button type="submit" class="site-btn">SEARCH</button>
            </form>
          </div>
          <div class="hero__search__phone">
            <div class="hero__search__phone__icon">
              <i class="fa fa-phone"></i>
            </div>
            <div class="hero__search__phone__text">
              <h5>+65 11.188.888</h5>
              <span>Support 24/7 time</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="blog-details-hero set-bg" data-setbg="{% static '' %}img/blog/details/details-hero.jpg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="blog__details__hero__text">
          <h2>{{ blog.name }}</h2>
          <ul>
            <li>By {{ blog.avtor }}</li>
            <li>{{ blog.created_at|date }}</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="blog-details spad">
  <div class="container">
    <div class="row">

      {% include 'lside.html' %}

      <div class="col-lg-8 col-md-7 order-md-1 order-1">
        <div class="blog__details__text">
          <img src="{{ blog.image.url }}" alt>
          <p>{{ blog.description|safe }}</p>
        </div>
        <div class="blog__details__content">
          <div class="row">
            <div class="col-lg-6">
              <div class="blog__details__author">
                <div class="blog__details__author__pic">
                  <img src="{% static '' %}img/blog/details/details-author.jpg" alt>
                </div>
                <div class="blog__details__author__text">
                  <h6>{{ blog.avtor }}</h6>
                  <span>Admin</span>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="blog__details__widget">
                <ul>
                  <li><span>Categories:</span> All, {% for cat in category %} {{ cat.name }} {% endfor %}</li>
                  <li><span>Tags:</span> All, {% for tag in blog.tags.all %} {{ tag.name }} {% endfor %}</li>
                </ul>
                <div class="blog__details__social">
                  <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                  <a href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a>
                  <a href="https://www.google.com/"><i class="fa fa-google-plus"></i></a>
                  <a href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a>
                  <a href="https://www.envelope.com/"><i class="fa fa-envelope"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="related-blog spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title related-blog-title">
          <h2>Post You May Like</h2>
        </div>
      </div>
    </div>
    <div class="row">
      {% for blog in blogs %}
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="blog__item">
          <div class="blog__item__pic">
            <img src="{{ blog.image.url }}" alt>
          </div>
          <div class="blog__item__text">
            <ul>
              <li><i class="fa fa-calendar-o"></i>{{ blog.created_at|date}}</li>
            </ul>
            <h5><a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a></h5>
            <p>{{ blog.description|safe|slice:"105"}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}

templates/blog.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="hero hero-normal">
  <div class="container">
    <div class="row">
      
      {% include 'categories.html '%}
      
      <div class="col-lg-9">
        <div class="hero__search">
          <div class="hero__search__form">
            <form action="#">
              <div class="hero__search__categories">
                All Categories
                <span class="arrow_carrot-down"></span>
              </div>
              <input type="text" name="query" placeholder="What do yo u need?">
              <button type="submit" class="site-btn">SEARCH</button>
            </form>
          </div>
          <div class="hero__search__phone">
            <div class="hero__search__phone__icon">
              <i class="fa fa-phone"></i>
            </div>
            <div class="hero__search__phone__text">
              <h5>+65 11.188.888</h5>
              <span>support 24/7 time</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="breadcrumb-section set-bg" data-setbg="{% static '' %}img/breadcrumb.jpg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="breadcrumb__text">
          <h2>Blog</h2>
          <div class="breadcrumb__option">
            <a href="{% url 'index' %}">Home</a>
            <span>Blog</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="blog spad">
  <div class="container">
    <div class="row">

      {% include 'lside.html' %}

      <div class="col-lg-8 col-md-7">
        <div class="row">
          {% for blog in blogs %}
          <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="blog__item">
              <div class="blog__item__pic">
                <img src="{{ blog.image.url }}" alt>
              </div>
              <div class="blog__item__text">
                <ul>
                  <li><i class="fa fa-calendar-o"></i>{{ blog.created_at|date }}</li>
                </ul>
                <h5><a href="{{ blog.get_absolute_url }}">{{ blog.name|slice:":40" }}...</a></h5>
                <p>{{ blog.description|safe|slice:":100" }}...</p>
                <a href="{{ blog.get_absolute_url }}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>
              </div>
            </div>
          </div>
          {% endfor %}

          {% include 'paginator.html' %}

        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/cart.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="hero hero-normal">
  <div class="container">
    <div class="row">

      {% include 'categories.html' %}

      <div class="col-lg-9">
        <div class="hero__search">
          <div class="hero__search__form">
            <form action="#">
              <div class="hero__search__categories">
                All Categories
                <span class="arrow_carrot-down"></span>
              </div>
              <input type="text" name="query" placeholder="What do yo u need?">
              <button type="submit" class="site-btn">SEARCH</button>
            </form>
          </div>
          <div class="hero__search__phone">
            <div class="hero__search__phone__icon">
              <i class="fa fa-phone"></i>
            </div>
            <div class="hero__search__phone__text">
              <h5>+65 11.188.888</h5>
              <span>support 24/7 time</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg' %}">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="breadcrumb__text">
          <h2>Shopping Cart</h2>
          <div class="breadcrumb__option">
            <a href="{% url 'index' %}">Home</a>
            <span>Shopping Cart</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="shoping-cart spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="shoping__cart__table">
          <table>
            <thead>
              <tr>
                <th class="shoping__product">Products</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {% for item in cart_items %}
              <tr>
                <td class="shoping__cart__item">
                  <img src="{{ item.product.images.first.image.url }}" width="150" height="150" alt>
                  <h5 style="font-weight: bold;">{{ item.product }}</h5>
                </td>
                <td class="shoping__cart__price">
                  $ {{ item.product.discount }}
                </td>
                <td class="shoping__cart__quantity">
                  <div class="quantity">
                    <div class="pro-qty">
                      <input type="text" value="{{ item.quantity }}" disabled>
                    </div>
                  </div>
                </td>
                <td class="shoping__cart__total">
                  $ {{ item.total }}
                </td>
                <td class="shoping__cart__item__close">
                  <a href="{% url 'remove_from_cart' item.id %}"><span class="icon_close"></span></a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="shoping__cart__btns">
          <a href="{% url 'shop' %}" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
        </div>
      </div>
      <div class="col-lg-6">

      </div>
      <div class="col-lg-6">
        <div class="shoping__checkout">
          <h5>Cart Total</h5>
          <ul>
            <li>Subtotal <span>$ {{ cart_total }}</span></li>
            <li>Total <span>$ {{ cart.main_total }}</span></li>
          </ul>
          <a href="{% url 'order' %}" class="primary-btn">PROCEED TO CHECKOUT</a>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/lside.html
{% load static %}

<div class="col-lg-4 col-md-5">
    <div class="blog__sidebar">
        <div class="blog__sidebar__search">
            <form action="#">
                <input type="text" name="query" placeholder="Search...">
                <button type="submit"><span class="icon_search"></span></button>
            </form>
        </div>
        <div class="blog__sidebar__item">
            <h4>Categories</h4>
            <ul>
                <li><a href="#">All</a></li>
                {% for cat in category %}
                <li><a href="?cat={{ cat.slug }}">{{ cat.name }} ({{ cat.blog_set.count }})</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="blog__sidebar__item">
            <h4>Recent News</h4>
            <div class="blog__sidebar__recent">
                {% for recent in recent_blogs %}
                <a href="{{ recent.get_absolute_url }}" class="blog__sidebar__recent__item">
                    <div class="blog__sidebar__recent__item__pic">
                        <img src="{{ recent.image.url }}" alt>
                    </div>
                    <div class="blog__sidebar__recent__item__text">
                        <h6>{{ recent.title }}</h6>
                        <span>{{ recent.created_at|date }}</span>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="blog__sidebar__item">
            <h4>Search By</h4>
            <div class="blog__sidebar__item__tags">
                {% for tag in tags %}
                <a href="?tag={{ tag.slug }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>